[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.build]
command = "cargo"
args = ["build", "--release", "-p", "example"]
dependencies = ["clean"]

[tasks.opt]
command = "wasm-opt"
args = [
    "-O2",
    "-Oz",
    "--strip-debug",
    "--strip-dwarf",
    "--dce",
    "--disable-multimemory",
    "--disable-fp16",
    "--disable-mutable-globals",
    "--disable-gc",
    "--disable-multivalue",
    "--disable-nontrapping-float-to-int",
    "--disable-threads",
    "--mvp-features",
    "--remove-unused-module-elements",
    "target/wasm32-unknown-unknown/release/example.wasm",
    "-o",
    "target/wasm32-unknown-unknown/release/example.wasm"
]
dependencies = ["build"]

[tasks.super]
command = "echo"
args = ["hello", "world"]
dependencies = ["build"]

[tasks.test]
command = "cargo"
args = ["test"]
dependencies = ["clean"]